const USER_ROLES = {
  ADMIN: 'ADMIN',
  PET_OWNER: 'PET_OWNER',
  VETERINARIAN: 'VETERINARIAN',
  PET_STORE: 'PET_STORE',
  PARAPHARMACY: 'PARAPHARMACY'
};

const USER_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED'
};

const PET_SPECIES = {
  DOG: 'DOG',
  CAT: 'CAT',
  BIRD: 'BIRD',
  RABBIT: 'RABBIT',
  REPTILE: 'REPTILE',
  FISH: 'FISH',
  HAMSTER: 'HAMSTER',
  GUINEA_PIG: 'GUINEA_PIG',
  FERRET: 'FERRET',
  HORSE: 'HORSE',
  OTHER: 'OTHER'
};

const PET_GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  NEUTERED: 'NEUTERED',
  SPAYED: 'SPAYED',
  UNKNOWN: 'UNKNOWN'
};

const APPOINTMENT_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
  REJECTED: 'REJECTED',
  RESCHEDULED: 'RESCHEDULED',
  PENDING_PAYMENT: 'PENDING_PAYMENT'
};

const APPOINTMENT_TYPE = {
  VISIT: 'VISIT',
  ONLINE: 'ONLINE'
};

const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  PARTIAL: 'PARTIAL'
};

const MEDICAL_RECORD_TYPE = {
  VACCINATION: 'VACCINATION',
  SURGERY: 'SURGERY',
  LAB_REPORT: 'LAB_REPORT',
  XRAY: 'XRAY',
  PRESCRIPTION: 'PRESCRIPTION',
  WEIGHT: 'WEIGHT',
  GENERAL: 'GENERAL',
  OTHER: 'OTHER'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  NONE: 'NONE'
};

const VETERINARY_SPECIALIZATION = {
  SMALL_ANIMAL: 'SMALL_ANIMAL',
  LARGE_ANIMAL: 'LARGE_ANIMAL',
  EXOTIC_ANIMALS: 'EXOTIC_ANIMALS',
  AVIAN: 'AVIAN',
  REPTILE: 'REPTILE',
  EMERGENCY: 'EMERGENCY',
  SURGERY: 'SURGERY',
  DERMATOLOGY: 'DERMATOLOGY',
  CARDIOLOGY: 'CARDIOLOGY',
  ONCOLOGY: 'ONCOLOGY',
  DENTISTRY: 'DENTISTRY',
  OPHTHALMOLOGY: 'OPHTHALMOLOGY',
  BEHAVIOR: 'BEHAVIOR',
  NUTRITION: 'NUTRITION',
  INTERNAL_MEDICINE: 'INTERNAL_MEDICINE',
  RADIOLOGY: 'RADIOLOGY'
};

const SERVICE_TYPE = {
  BOARDING: 'BOARDING',
  DAYCARE: 'DAYCARE',
  GROOMING: 'GROOMING',
  TRAINING: 'TRAINING',
  PET_SITTING: 'PET_SITTING',
  CONSULTATION: 'CONSULTATION'
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  PET_SPECIES,
  PET_GENDER,
  APPOINTMENT_STATUS,
  APPOINTMENT_TYPE,
  PAYMENT_STATUS,
  MEDICAL_RECORD_TYPE,
  ORDER_STATUS,
  SUBSCRIPTION_STATUS,
  VETERINARY_SPECIALIZATION,
  SERVICE_TYPE,
  HTTP_STATUS
};
